<template>
    <div class="container-fluid">
        <div id="header" class="row animated fadeInDown">
            <h3 class="display-4"><a href="https://en.wikipedia.org/wiki/Periodic_table">Periodic Table of Elements<span class="underline"></span></a></h3>
            <h4>In memory of <a href="https://en.wikipedia.org/wiki/Dmitri_Mendeleev">Dmitri Mendeleev<span class="underline"></span></a></h4>
        </div>

        <div id="content" class="row row-centered animated slideInLeft">
            <div id="periodictable" ref="periodictable">
                <!-- Generated by JavaScript - Made this before the likes of React/Vue existed -->
            </div>
        </div>

        <div id="footer" class="row animated fadeInUp">
            <div class="col-5 footquote">
                <blockquote class="blockquote text-right align-middle animated slideInLeft">
                    <p class="mb-0">No one nor anything can silence me.</p>
                    <footer class="blockquote-footer">Dmitri Mendeleev</footer>
                </blockquote>
            </div>
            <div class="col-2 footquote">
                <img class="portrait img-fluid mx-auto" src="https://upload.wikimedia.org/wikipedia/commons/8/8f/Dmitri_Mendeleev_1890s.jpg"></img>
            </div>
            <div class="col-5 footquote ">
                <p class="summary animated slideInRight">Dmitri Ivanovich Mendeleev was a Russian chemist and inventor. He formulated the Periodic Law, created a farsighted version of the periodic table of elements, and used it to correct the properties of some already discovered elements and also to predict the properties of eight elements yet to be discovered.</p>
            </div>
        </div>
    </div>
</template>

<script>
    import 'animate.css';
    import 'assets/portfolio/bootstrap-4.0.0-beta.min.css'
    import PeriodicTable from 'assets/portfolio/PeriodicTableJSON';

    console.log(PeriodicTable);


    export default {
        name: 'periodic-table-of-elements',
        layout: 'portfolio',
        mounted() {
            let blocks = 1,
                htmlString = '',
                string = '',
                tooltipPosition,
                counter = 3,
                lastrows = '<div class="row lastrow">' + '<div class="element col-18 empty"></div>'.repeat(3);

            PeriodicTable.elements.map((element, i) => {
                // Make Tooltip appear to the left or right of element
                if (blocks > 9 || i === 1 || i === 4 || i === 12 || (i >= 62 && i <= 70) || (i >= 94 && i <= 102)) {
                    tooltipPosition = " lefttip";
                } else {
                    tooltipPosition = ' righttip';
                }

                // tooltip vertical positioning
                if (i < 54) {
                    tooltipPosition += " downtip";
                } else {
                    tooltipPosition += " uptip";
                }

                string = `<div class="element animated zoomIn col-18 ${element.category.replace(/\s+/g, '')}">
<a href="${element.source}">
    <p class="elementnumber">${element.number}</p>
    <h2 class="elementsymbol">${element.symbol}</h2>
    <p class="elementname">${element.name}</p>
    <p class="elementmass">${element.atomic_mass}</p>
</a>
<span class="tooltip ${element.category.replace(/\s+/g, '')} ${tooltipPosition}">
<p class="tpsymbol">${element.symbol}</p>
<p class="tpname">${element.name}</p>
<p class="tpmass">${element.atomic_mass}</p>
<p class="tpcat">${element.category}</p>
${element.appearance && `<p class="tpapp"><b>Appearance:</b> ${element.appearance}</p>`}
${element.boil && `<p class="tpbp"><b>Boiling Point:</b> ${element.boil}</p>`}
<p class="tpdensity"><b>Density:</b> ${element.density}</p>
<p class="tpphase"><b>Phase:</b> ${element.phase}</p>
${element.discovered_by && `<p class="tpdisc"><b>Discovered by:</b> ${element.discovered_by}</p>`}
${element.named_by && `<p class="tpnamed"><b>Named by:</b> ${element.named_by}</p>`}
<p class="tpsummary"><b>Summary:</b> ${element.summary}</p>
</span>
</div>
`;
                // Add white blocks for spacing on second, fifth and thirteenth
                // iteration and the eight and ninth row of the table
                if (i == 1) {
                    blocks += 16;
                    htmlString += '<div class="element col-18 empty"></div>'.repeat(16);
                } else if (i == 4 || i == 12) {
                    blocks += 10;
                    htmlString += '<div class="element col-18 empty"></div>'.repeat(10);
                } else if ((i >= 56 && i <= 70) || (i >= 88 && i <= 102)) {
                    if (i == 56) {
                        htmlString += '<div class="element elespacer animated zoomIn col-18"><p>57-71</p></div>';
                        blocks++;
                    } else if (i == 88) {
                        htmlString += '<div class="element elespacer animated zoomIn col-18"><p>67-103</p></div>';
                        blocks++;
                    }
                    lastrows += string;
                    counter++;
                    if (counter == 18) {
                        lastrows += '</div><div class="row">' + '<div class="element col-18 empty"></div>'.repeat(3);
                        counter = 3;
                    }
                    return;
                }

                switch (blocks) {
                    case 1:
                        htmlString += '<div class="row">' + string;
                        break;
                    case 18:
                        htmlString += string + '</div>';
                        blocks = 0;
                        break;
                    default:
                        htmlString += string;
                        if (i + 1 === PeriodicTable.elements.length) {
                            htmlString += "</div>";
                        }
                }

                blocks++;
            });

            htmlString += lastrows + "</div>";

            const div = document.createElement('div');
            // div.innerHTML = htmlString;
            this.$refs.periodictable.innerHTML = htmlString;
        }
    }
</script>

<style lang="scss">
    // Element Categories
    $metalloids: #77DD88;
    $alkali-metals: #FFCC33;
    $alkaline-earth-metals: #FFFF44;
    $lanthanoids: #FFBB99;
    $transition-metals: #DDBBBB;
    $post-transition-metals: #99DDCC;
    $other: #22FF22;
    $noble-gases: #77CCFF;
    $actinoids: #EEBBDD;
    $unknown: #d3d3d3;

    // Misc
    $ptbackground: aliceblue;
    $header: #e4e4e4;
    $footer: $header;

    .container-fluid {
        overflow: hidden;
    }

    #header {
        border-radius: 5px 5px 0 0;
        margin-top: 20px;
        background-color: $header;
        text-align: center;
        font-stretch: extra-condensed;
        user-select: none;
        animation-delay: .5s;

        a {
            display: inline-block;
            color: inherit;
            text-decoration: inherit;
        }

        a:hover .underline {
            transform: scaleX(1);
        }

        h3 {
            color: darken($header, 50%);
            font-size: 4vw;
            width: 100%;
            margin-top: 1%;
            margin-bottom: 0;

            .underline {
                height: .2vw;
                background-color: darken($header, 50%);
            }
        }

        h4 {
            color: white; //darken($header, 20%);
            font-size: 1.5vw;
            font-weight: 100;
            width: 100%;
        }
    }

    .underline {
        display: block;
        position: relative;
        padding: 0;
        width: 100%;
        height: .15vw;
        right: 0;
        background-color: white;
        transition: all .5s ease-in-out 0s;
        transform: scaleX(0);
    }

    #content {
        margin: 0;
        padding: 10px 0;
        background-color: $ptbackground;
    }

    #periodictable {
        width: 100%;
    }

    #footer {
        animation-delay: .5s;
        margin: 0 0 10px;
        background-color: $footer;
        border-radius: 0 0 5px 5px;
    }

    .portrait {
        margin: 5px;
        max-height: 120px;
        border-color: darken($footer, 10%);
        border-width: 5px;
        border-style: solid;
        border-radius: 50%;
    }

    .footquote {
        display: flex;
        align-items: center;
        justify-content: flex-end;

        blockquote, .summary {
            animation-delay: 1s;
            margin: 0;
            padding: 10px;
            font-size: 1.4vw;
        //color: darken($footer, 40%);
        //border-radius: 10px;
            background-color: lighten($footer, 5%);
        }

        .summary {
            font-size: 1vw;
        }
    }

    .row {
        display: flex;
        margin: 0;
    }

    .element {
        animation-delay: 1s;
        border-radius: 5px;
        box-shadow:0 0 0 1px $ptbackground inset;
        color: lighten($unknown, 20%);
        background-color: $unknown;
        transition: background-color .3s ease-in-out 0s;

        .elementsymbol {
            color: darken($unknown, 40%);
        }

        a {
            color: inherit;
            text-decoration: inherit;
        }

        &:hover {
            background-color: lighten($unknown, 5%);
        }

        &:hover .tooltip {
            visibility: visible;
            opacity: 1;
            z-index: 10;
        }
    }

    .elementnumber {
        position: absolute;
        padding: 2px 4px 0 0;
        font-size: .8vw;
        text-align: right;
        width: 100%;
    }

    .elementsymbol {
        padding-top: 2px;
        margin-left: 5px;
        font-size: 2.2vw;
        text-align: left;
    }

    .elementname {
        margin: -10px 3px 0px 5px;
        font-size: .8em;
        font-stretch: extra-condensed;
        font-family: sans-serif;
        text-align: left;
        overflow: hidden;
        text-overflow: clip;
    }

    .elementmass {
        margin: 0 3px 3px 3px;
        text-align: left;
        font-size: .8vw;
        overflow: hidden;
        text-overflow: clip;
    }

    .empty {
        box-shadow: none;
        background-color: transparent;
        &:hover {
            background-color: inherit;
        }
    }

    .tooltip {
        visibility: hidden;
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        position: absolute;
        border-radius: 6px;
        width: 800%;
        padding: 5px 0;
        color: #fff;
        background-color: $unknown;
        font-size: 1.5vw;
        text-align: center;
        z-index: -1;
        opacity: 0;
        transition: opacity .3s;
        pointer-events: none;

        p {
            margin-bottom: 0;
        }

        .tpsymbol {
            flex-basis: 100%;
            font-size: 3vw;
        }

        .tpname, .tpmass, .tpcat {
            flex-basis: 100%;
        }

        .tpcat {
            margin-bottom: 8px;
            text-transform: capitalize;
        }

        .tpapp {
            text-transform: capitalize;
        }

        .tpapp, .tpbp, .tpdensity, .tpphase, .tpdisc, .tpnamed, .tpsummary {
            text-align: left;
            margin: 0 4% 5px 4%;
        }

        .tpsummary {
            font-size: 1.4vw;
            margin-bottom: 4%;
        }
    }

    .righttip {
        left: 101%;
    }

    .lefttip {
        right: 101%;
    }

    .downtip {
        top: -50%;
    }

    .uptip {
        bottom: -50%;
    }

    // Period Table 18 columns
    .col-18 {
        position: relative;
        flex: 0 0 5.555556%;
        max-width: 5.555556%;
        width: 100%;
        min-height: 1px;
    }

    .elespacer {
        display: flex;
        font-size: 1.2vw;
        text-align: center;
        align-items: center;
        background-color: #c99;
        cursor: default;
        p {
            width: 100%;
            margin: 0;
        }
        &:hover {
            background-color: #c99;
        }
    }

    .elespacer:hover #header {
        background-color: lighten($lanthanoids, 5%)!important;
    }

    .lastrow {
        margin-top: 10px;
    }

    .animated {
        -webkit-animation-duration:1s;
        animation-duration:1s;
        -webkit-animation-fill-mode:backwards!important;
        animation-fill-mode:backwards!important
    }

    @media only screen and (max-width: 500px) {
        .elementnumber, .elementname, .elementmass, .footquote blockquote, .summary {
            display:none;
        }
    }

    // Element Categories
    .diatomicnonmetal {
        .elementsymbol{
            color: darken($other, 40%);
        }
        .elementname, .tooltip {
            color: lighten($other, 40%);
        }
        &:hover {
            background-color: lighten($other, 20%);
        }
        background-color: $other;
    }

    .noblegas {
        .elementsymbol{
            color: darken($noble-gases, 40%);
        }
        .elementname, .tooltip {
            color: lighten($noble-gases, 20%);
        }
        &:hover {
            background-color: lighten($noble-gases, 10%);
        }
        background-color: $noble-gases;
    }

    .alkalimetal {
        .elementsymbol{
            color: darken($alkali-metals, 40%);
        }
        .elementname, .tooltip {
            color: lighten($alkali-metals, 40%);
        }
        &:hover {
            background-color: lighten($alkali-metals, 10%);
        }
        background-color: $alkali-metals;
    }

    .alkalineearthmetal {
        .elementsymbol{
            color: darken($alkaline-earth-metals, 40%);
        }
        .elementname, .elementmass, .elementnumber, .tooltip {
            color: darken($alkaline-earth-metals, 40%);
        }
        &:hover {
            background-color: lighten($alkaline-earth-metals, 20%);
        }
        background-color: $alkaline-earth-metals;
    }

    .metalloid {
        .elementsymbol {
            color: darken($metalloids, 40%);
        }
        .elementname, .tooltip {
            color: lighten($metalloids, 30%);
        }
        &:hover {
            background-color: lighten($metalloids, 10%);
        }
        background-color: $metalloids;
    }

    .polyatomicnonmetal {
        .elementsymbol{
            color: darken($other, 40%);
        }
        .elementname, .tooltip {
            color: lighten($other, 40%);
        }
        &:hover {
            background-color: lighten($other, 20%);
        }
        background-color: $other;
    }

    .post-transitionmetal {
        .elementsymbol{
            color: darken($post-transition-metals, 40%);
        }
        .elementname, .tooltip {
            color: lighten($post-transition-metals, 20%);
        }
        &:hover {
            background-color: lighten($post-transition-metals, 10%);
        }
        background-color: $post-transition-metals;
    }

    .transitionmetal {
        .elementsymbol{
            color: darken($transition-metals, 40%);
        }
        .elementname, .tooltip {
            color: lighten($transition-metals, 20%);
        }
        &:hover {
            background-color: lighten($transition-metals, 5%);
        }
        background-color: $transition-metals;
    }

    .actinide {
        .elementsymbol{
            color: darken($actinoids, 40%);
        }
        .elementname, .tooltip {
            color: lighten($actinoids, 20%);
        }
        &:hover {
            background-color: lighten($actinoids, 5%);
        }
        background-color: $actinoids;
    }

    .lanthanide {
        .elementsymbol{
            color: darken($lanthanoids, 40%);
        }
        .elementname, .tooltip {
            color: lighten($lanthanoids, 20%);
        }
        &:hover {
            background-color: lighten($lanthanoids, 5%);
        }
        background-color: $lanthanoids;
    }
</style>
